# Generated by Django 3.2.6 on 2021-10-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.EmailField(max_length=100, verbose_name='email')),
                ('following', models.EmailField(max_length=100, verbose_name='email')),
                ('is_live', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'follow',
            },
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='follower-following'),
        ),
    ]
