# Generated by Django 3.2.6 on 2021-10-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='user_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
