# Generated by Django 3.2.6 on 2021-10-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_feed_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='email'),
        ),
    ]
