# Generated by Django 3.2.6 on 2021-10-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_feed_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('is_like', models.BooleanField(default=False)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(blank=True, max_length=30, null=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['feed_id'], name='content_rep_feed_id_49ae3d_idx'),
        ),
        migrations.AddIndex(
            model_name='feedlike',
            index=models.Index(fields=['feed_id'], name='content_fee_feed_id_1c82cf_idx'),
        ),
        migrations.AddIndex(
            model_name='feedlike',
            index=models.Index(fields=['email'], name='content_fee_email_3901d6_idx'),
        ),
    ]
