# Generated by Django 3.2.6 on 2021-10-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20211011_2128'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='feedlike',
            name='content_fee_email_3901d6_idx',
        ),
    ]
