# Generated by Django 3.2.6 on 2021-10-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_feedlike_content_fee_email_3901d6_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feedlike',
            index=models.Index(fields=['email'], name='content_fee_email_3901d6_idx'),
        ),
    ]
