# Generated by Django 3.2.6 on 2021-10-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_feedlike_content_fee_email_3901d6_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedlike',
            name='content',
        ),
        migrations.AddField(
            model_name='reply',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='email'),
        ),
    ]
