# Generated by Django 3.2.6 on 2021-10-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20211012_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('feed_id', models.IntegerField()),
                ('is_bookmarked', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['email'], name='content_boo_email_03c3c8_idx'),
        ),
    ]
